import type { Listing } from "./types";

// Fixed timestamps keep server and client renders identical.
const BASE_TIME = Date.UTC(2026, 8, 1);

export const DEMO_LISTINGS: readonly Listing[] = [
  {
    id: "demo-aundh",
    title: "Aundh Sai Heritage 3BHK",
    totalRent: 42000,
    deposit: 126000,
    floor: 3,
    hasLift: true,
    hasParking: true,
    petFriendly: true,
    bathrooms: 3,
    hinjewadiCommute: 30,
    gymCommute: 15,
    addedBy: "kavita",
    createdAt: BASE_TIME + 4,
  },
  {
    id: "demo-kothrud",
    title: "Kothrud Shanti Niwas 3BHK",
    totalRent: 39000,
    deposit: 100000,
    floor: 3,
    hasLift: false,
    hasParking: true,
    petFriendly: false,
    bathrooms: 2,
    hinjewadiCommute: 35,
    gymCommute: 18,
    addedBy: "riya",
    createdAt: BASE_TIME + 3,
  },
  {
    id: "demo-baner",
    title: "Baner High Street 3BHK",
    totalRent: 42000,
    deposit: 150000,
    floor: 5,
    hasLift: true,
    hasParking: true,
    petFriendly: true,
    bathrooms: 2,
    hinjewadiCommute: 50,
    gymCommute: 12,
    addedBy: "meera",
    createdAt: BASE_TIME + 2,
  },
  {
    id: "demo-viman-nagar",
    title: "Viman Nagar Skyline 3BHK",
    totalRent: 48000,
    deposit: 200000,
    floor: 4,
    hasLift: false,
    hasParking: false,
    petFriendly: false,
    bathrooms: 2,
    hinjewadiCommute: 65,
    gymCommute: 25,
    addedBy: "riya",
    createdAt: BASE_TIME + 1,
  },
];
